2024-12-13 12:33:34,989 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Configure stats pid to 24232
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Loading settings from C:\Users\chawk\.config\wandb\settings
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Loading settings from G:\My Drive\Junior Year\CS 175\Project\Code\gym-rocketlander\wandb\settings
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'gym_rocketlander\\PPO.py', 'program_abspath': 'G:\\My Drive\\Junior Year\\CS 175\\Project\\Code\\gym-rocketlander\\gym_rocketlander\\PPO.py', 'program': 'G:\\My Drive\\Junior Year\\CS 175\\Project\\Code\\gym-rocketlander\\gym_rocketlander\\PPO.py'}
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_init.py:_log_setup():533] Logging user logs to G:\My Drive\Junior Year\CS 175\Project\Code\gym-rocketlander\wandb\run-20241213_123334-rid5pgaa\logs\debug.log
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_init.py:_log_setup():534] Logging internal logs to G:\My Drive\Junior Year\CS 175\Project\Code\gym-rocketlander\wandb\run-20241213_123334-rid5pgaa\logs\debug-internal.log
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_init.py:init():619] calling init triggers
2024-12-13 12:33:34,998 INFO    MainThread:24232 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0003, 'batch_size': 64, 'policy': 'MlpPolicy', 'env_name': 'RocketLander-v0', 'total_timesteps': 100000}
2024-12-13 12:33:35,005 INFO    MainThread:24232 [wandb_init.py:init():669] starting backend
2024-12-13 12:33:35,005 INFO    MainThread:24232 [wandb_init.py:init():673] sending inform_init request
2024-12-13 12:33:35,027 INFO    MainThread:24232 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2024-12-13 12:33:35,027 INFO    MainThread:24232 [wandb_init.py:init():686] backend started and connected
2024-12-13 12:33:35,074 INFO    MainThread:24232 [wandb_init.py:init():781] updated telemetry
2024-12-13 12:33:35,242 INFO    MainThread:24232 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-12-13 12:33:36,950 ERROR   MainThread:24232 [wandb_init.py:init():841] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your_username not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-13 12:33:36,950 ERROR   MainThread:24232 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\chawk\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 1256, in init
    return wi.init()
  File "C:\Users\chawk\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your_username not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-13 12:33:37,013 WARNING MsgRouterThr:24232 [router.py:message_loop():75] message_loop has been closed
